version: '3'

services:
  server-php7:
    build: 
      context: ./php
      dockerfile: Dockerfile_PHP_74
    volumes: 
      - ./../src:/var/www/html
      - ./php/logs:/var/log/apache2/logs
      - ./php/composer:/var/www/.composer
    ports: 
      - "80:80"
      - "443:443"
  server:
    build:
      context: ./php
      dockerfile: Dockerfile_PHP_8
    volumes: 
      - ./../src:/var/www/html
      - ./php/logs:/var/log/apache2/logs
      - ./php/composer:/var/www/.composer
    ports: 
      - "80:80"
      - "443:443"
    depends_on: 
      - database
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./database:/var/lib/mysql
    ports: 
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on: 
      - database
  mongo_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: e296cd9f
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    command: mongod --auth