FROM php:7.4-apache

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions gd zip xdebug mysqli pdo_mysql opcache mongodb
RUN apt-get update; \ 
    apt-get install -y\
    zip \
    unzip

COPY ./conf.d /usr/local/etc/php/conf.d

# Enable apache rewrite
COPY ./sites-available /etc/apache2/sites-available

RUN a2enmod rewrite

RUN a2ensite *.conf

VOLUME ["/var/log/apache2/logs/"]

ENV PHP_XDEBUG 1
ENV PHP_TIMEZONE "UTC+3"

# Show all apache configs
# RUN apache2ctl -S

USER www-data